import {TrackingAdapter} from './tracking.js';
import {WorldEngine} from './world-engine.js';

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const video=$('#camera'),xrCanvas=$('#xrCanvas'),scanOverlay=$('#scanOverlay'),sctx=scanOverlay.getContext('2d');
const tracking=new TrackingAdapter();let world=null,stream=null,currentElement='LAV',started=false,quality='MEDIUM',meshVisible=true;
const ELEMENTS=[['🌋','LAV'],['🌊','SU'],['❄️','BUZ'],['🌱','ÇİMEN'],['🏜️','KUM'],['☁️','BULUT'],['🌌','UZAY'],['🟣','VOID'],['💎','KRİSTAL'],['🔥','ATEŞ'],['🧊','DONMUŞ'],['🍄','MANTAR'],['🌲','ORMAN'],['🌑','AY'],['☣️','TOKSİK'],['🌈','GÖKKUŞAĞI'],['⚡','ELEKTRİK'],['🪨','TAŞ'],['🏙️','CYBERPUNK'],['👾','GLITCH']];
function toast(t){const e=$('#readyToast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),1600)}
function resizeOverlay(){const d=Math.min(devicePixelRatio||1,1.5);scanOverlay.width=innerWidth*d;scanOverlay.height=innerHeight*d;scanOverlay.style.width=innerWidth+'px';scanOverlay.style.height=innerHeight+'px';sctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resizeOverlay);resizeOverlay();

async function startCamera(){
 try{
  if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}
  const mode=await tracking.start(xrCanvas);
  if(mode==='xr8'){
    video.classList.add('hidden');xrCanvas.classList.remove('hidden');
  }else{
    xrCanvas.classList.add('hidden');video.classList.remove('hidden');
    if(!navigator.mediaDevices?.getUserMedia)throw new Error('Kamera desteklenmiyor');
    stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();
  }
  $('#permissionCard').classList.add('hidden');if(!world){world=new WorldEngine($('#worldLayer'),tracking);world.start();}started=true;await runScan();updateCapability();
 }catch(err){console.error(err);$('#permissionCard p').textContent='AR kamera açılamadı. Safari kamera iznini kontrol et.';}
}
function updateCapability(){const q=tracking.getPose().quality;$('#modeBadge').textContent=q==='xr8'?'8TH WALL • WORLD LOCK':q==='xr8-limited'?'8TH WALL • INITIALIZING':q==='orientation'?'FALLBACK • ORIENTATION':'FALLBACK';$('#surfaceConfidence').textContent=q==='xr8'?'SLAM NORMAL':q==='xr8-limited'?'SLAM LIMITED':'ESTIMATED';$('#capabilityText').textContent=q.startsWith('xr8')?'8th Wall SLAM aktif: pozisyon + dönüş (6DoF) world tracking kullanılıyor. Dünya kamera ekranına değil takip edilen dünya koordinatına bağlıdır.':'8th Wall SLAM bu cihazda başlamadı; hareket sensörlü fallback kullanılıyor.'}
async function runScan(){const hud=$('#scanHud'),bar=$('#scanProgress'),text=$('#scanText'),surface=$('#surfaceHud');hud.classList.remove('hidden');surface.classList.add('hidden');let p=0;await new Promise(r=>{const timer=setInterval(()=>{p+=5+Math.random()*7;bar.style.width=Math.min(p,100)+'%';const q=tracking.getPose().quality;text.textContent=q.startsWith('xr8')?(p<40?'SLAM dünya noktaları aranıyor…':p<75?'6DoF pozisyon kilitleniyor…':'Dünya koordinatı sabitleniyor…'):(p<50?'Hareket sensörü kalibre ediliyor…':'Fallback dünya düzlemi hazırlanıyor…');drawScan(Math.min(p,100)/100);if(p>=100){clearInterval(timer);r()}},120)});sctx.clearRect(0,0,innerWidth,innerHeight);tracking.recenter();world?.recenter();hud.classList.add('hidden');surface.classList.remove('hidden');toast('DÜNYA HAZIR')}
function drawScan(progress){sctx.clearRect(0,0,innerWidth,innerHeight);sctx.save();sctx.strokeStyle='rgba(93,235,255,.28)';sctx.lineWidth=1;const h=innerHeight*(.42+.08*(1-progress));for(let i=0;i<8;i++){const t=i/7,y=h+(innerHeight-h)*Math.pow(t,1.35),half=innerWidth*(.12+.48*t);sctx.beginPath();sctx.moveTo(innerWidth/2-half,y);sctx.lineTo(innerWidth/2+half,y);sctx.stroke()}for(let i=-5;i<=5;i++){sctx.beginPath();sctx.moveTo(innerWidth/2+i*12,h);sctx.lineTo(innerWidth/2+i*innerWidth*.12,innerHeight);sctx.stroke()}sctx.restore()}

const grid=$('#elementGrid');ELEMENTS.forEach(([icon,name],i)=>{const b=document.createElement('button');b.innerHTML=`${icon}<span>${name}</span>`;if(i===0)b.classList.add('selected');b.onclick=()=>{currentElement=name;[...grid.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};grid.appendChild(b)});
function openPanel(id){$$('.panel').forEach(p=>p.classList.add('hidden'));$(id).classList.remove('hidden')}$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#settingsBtn').onclick=()=>openPanel('#settingsPanel');$('#startBtn').onclick=startCamera;$('#cameraFlipBtn').onclick=()=>toast('8th Wall world tracking arka kamerayı kullanır');$('#applyFloorBtn').onclick=()=>{world?.setElement(currentElement);$('#elementsPanel').classList.add('hidden');toast(`${currentElement} • TÜM TABAN`)};$('#recalibrateBtn').onclick=runScan;$('#qualitySelect').onchange=e=>{quality=e.target.value;world?.setQuality(quality);toast('QUALITY • '+quality)};$('#meshToggle').onchange=e=>{meshVisible=e.target.checked;world?.setGridVisible(meshVisible)};$('#motionToggle').onchange=e=>{tracking.setEnabled(e.target.checked);updateCapability()};
$$('.toolbar button').forEach(btn=>btn.onclick=()=>{$$('.toolbar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const tool=btn.dataset.tool;if(tool==='elements')openPanel('#elementsPanel');else if(tool==='ai')openPanel('#aiPanel');else if(tool==='portal'){const on=world?.togglePortal();toast(on?'🌀 PORTAL AÇILDI':'PORTAL KAPANDI')}else if(tool==='chaos'){world?.setElement('ELEKTRİK');toast('⚡ CHAOS')}else if(tool==='spawn')toast('🐉 Creature modeli sonraki adım');else toast('🎮 Mini Games sonraki adım')});
$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#aiPrompt').value=b.dataset.prompt});$('#aiGenerateBtn').onclick=async()=>{const p=$('#aiPrompt').value.trim();if(!p)return toast('Bir dünya tarif et');await sendAI(p)};
async function sendAI(prompt){$('#aiStatus').textContent='AI düşünüyor…';try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt})});if(!r.ok)throw new Error(await r.text());const d=await r.json();applyPlan(d.plan||d);$('#aiStatus').textContent='AI planı uygulandı.'}catch(err){console.warn(err);applyPlan(localPlan(prompt));$('#aiStatus').textContent='Yerel komut motoru kullanıldı.'}}
function localPlan(text=''){const s=text.toLocaleLowerCase('tr');let e='KRİSTAL';if(s.includes('lav'))e='LAV';else if(s.includes('buz')||s.includes('dondur'))e='BUZ';else if(s.includes('su'))e='SU';else if(s.includes('orman'))e='ORMAN';else if(s.includes('uzay'))e='UZAY';else if(s.includes('cyber')||s.includes('neon'))e='CYBERPUNK';return {actions:[{type:'paint',element:e},{type:s.includes('portal')?'portal':'noop'}]}}
function applyPlan(plan){for(const a of plan.actions||[]){if(a.type==='paint'&&a.element){currentElement=a.element;world?.setElement(a.element)}if(a.type==='portal')world?.togglePortal(true)}$('#aiPanel').classList.add('hidden');toast('✨ AI WORLD APPLIED')}
$('#voiceBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Sesli komut desteklenmiyor');const rec=new SR();rec.lang='tr-TR';rec.start();toast('🎙️ Dinliyorum…');rec.onresult=e=>sendAI(e.results[0][0].transcript)};
$('#photoBtn').onclick=()=>{if(!started)return toast('Önce AR başlat');const out=document.createElement('canvas');out.width=innerWidth;out.height=innerHeight;const o=out.getContext('2d');try{o.drawImage(xrCanvas.classList.contains('hidden')?video:xrCanvas,0,0,out.width,out.height)}catch{}const gl=$('#worldLayer canvas');if(gl)o.drawImage(gl,0,0,out.width,out.height);out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mirrorrealm-'+Date.now()+'.jpg';a.click()},'image/jpeg',.92)};
updateCapability();