const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#xrCanvas');
let xrScene=null,ground=null,reticle=null,selected=null,current='sofa',started=false,tracking='INITIALIZING';
const items=[];const raycaster=new THREE.Raycaster();const tap=new THREE.Vector2();
const catalog=[['🛋️','sofa','floor'],['🪑','chair','floor'],['🪴','plant','floor'],['💡','lamp','floor'],['🗄️','cabinet','floor'],['🛏️','bed','floor'],['🧸','decor','floor'],['🖼️','picture','wall'],['📺','tv','wall'],['🪞','mirror','wall'],['🕰️','clock','wall'],['📚','shelf','wall']];
function toast(t){const e=$('#readyToast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),1400)}
function mat(c,r=.68,m=.03){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function addMesh(g,geo,material,x=0,y=0,z=0){const o=new THREE.Mesh(geo,material);o.position.set(x,y,z);g.add(o);return o}
function make(type){
 const g=new THREE.Group();g.userData.type=type;
 if(type==='sofa'){addMesh(g,new THREE.BoxGeometry(1.65,.38,.72),mat(0xb39b7d),0,.27,0);addMesh(g,new THREE.BoxGeometry(1.55,.62,.18),mat(0x8e775e),0,.7,.26);addMesh(g,new THREE.BoxGeometry(.18,.5,.72),mat(0x806a54),-.82,.45,0);addMesh(g,new THREE.BoxGeometry(.18,.5,.72),mat(0x806a54),.82,.45,0)}
 else if(type==='chair'){addMesh(g,new THREE.BoxGeometry(.62,.12,.62),mat(0xc49b68),0,.52,0);for(const x of[-.23,.23])for(const z of[-.23,.23])addMesh(g,new THREE.BoxGeometry(.07,.5,.07),mat(0x6a4b31),x,.25,z);addMesh(g,new THREE.BoxGeometry(.62,.68,.09),mat(0xb68550),0,.9,.26)}
 else if(type==='plant'){addMesh(g,new THREE.CylinderGeometry(.24,.31,.36,20),mat(0xa85f38),0,.18,0);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const l=addMesh(g,new THREE.SphereGeometry(.17,12,8),mat(0x3d8f4c),Math.cos(a)*.16,.55+Math.sin(i*1.7)*.07,Math.sin(a)*.16);l.scale.set(.55,1.8,.45)}}
 else if(type==='lamp'){addMesh(g,new THREE.CylinderGeometry(.17,.2,.06,20),mat(0x333333,.4,.35),0,.03,0);addMesh(g,new THREE.CylinderGeometry(.025,.025,1.1,12),mat(0x555555,.4,.45),0,.6,0);addMesh(g,new THREE.ConeGeometry(.31,.42,24,1,true),mat(0xf0d7a3),0,1.24,0)}
 else if(type==='bed'){addMesh(g,new THREE.BoxGeometry(1.55,.35,2.05),mat(0xd7d1ca),0,.26,0);addMesh(g,new THREE.BoxGeometry(1.55,.62,.12),mat(0x8a735f),0,.58,.96)}
 else if(type==='cabinet'){addMesh(g,new THREE.BoxGeometry(1.0,1.45,.48),mat(0x8e6849),0,.73,0)}
 else if(type==='decor'){addMesh(g,new THREE.SphereGeometry(.32,20,16),mat(0xc98f56),0,.32,0)}
 else {const col=type==='tv'?0x111317:type==='mirror'?0xbfe7ee:type==='picture'?0xb85d55:0x927252;const w=type==='clock'?.68:type==='shelf'?1.25:1.1,h=type==='clock'?.68:type==='shelf'?.35:.72;addMesh(g,new THREE.BoxGeometry(w,h,.06),mat(col,type==='mirror'?.18:.65,type==='mirror'?.6:.03),0,0,0)}
 return g;
}
function updateStatus(){const status=$('#surfaceConfidence');status.textContent=tracking;$('#modeBadge').textContent=tracking==='NORMAL'?'8TH WALL • WORLD LOCK':'8TH WALL • '+tracking;$('#capabilityText').textContent=tracking==='NORMAL'?'SLAM NORMAL: ürünler 8th Wall dünya koordinatlarında kalır.':'SLAM henüz NORMAL değil. Yerleştirme kapalı; telefonu yavaşça hareket ettir ve zeminde detaylı bir alan göster.'}
function createReticle(){const r=new THREE.Mesh(new THREE.RingGeometry(.11,.14,32).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0x73f2ff,transparent:true,opacity:.9,side:THREE.DoubleSide}));r.visible=false;r.position.y=.006;return r}
function initScene(){
 xrScene=XR8.Threejs.xrScene();const {scene,camera}=xrScene;scene.add(new THREE.HemisphereLight(0xffffff,0x59606b,2.2));
 ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshBasicMaterial({transparent:true,opacity:0,side:THREE.DoubleSide}));ground.rotation.x=-Math.PI/2;ground.position.y=0;scene.add(ground);
 reticle=createReticle();scene.add(reticle);camera.position.set(0,1.6,0);XR8.XrController.updateCameraProjectionMatrix({origin:camera.position,facing:camera.quaternion});
 loadSaved();
}
function placeFloor(clientX,clientY){if(!xrScene||tracking!=='NORMAL')return toast('ÖNCE WORLD TRACKING NORMAL OLSUN');const {camera,scene}=xrScene;tap.set(clientX/innerWidth*2-1,-clientY/innerHeight*2+1);raycaster.setFromCamera(tap,camera);const hit=raycaster.intersectObject(ground,false)[0];if(!hit)return toast('ZEMİN NOKTASI BULUNAMADI');const obj=make(current);obj.position.copy(hit.point);obj.position.y=0;scene.add(obj);items.push(obj);selected=obj;toast('YERLEŞTİRİLDİ')}
function placeWall(clientX,clientY){if(!xrScene||tracking!=='NORMAL')return toast('ÖNCE WORLD TRACKING NORMAL OLSUN');const {camera,scene}=xrScene;tap.set(clientX/innerWidth*2-1,-clientY/innerHeight*2+1);raycaster.setFromCamera(tap,camera);const obj=make(current);const distance=2.25;obj.position.copy(raycaster.ray.origin).add(raycaster.ray.direction.clone().multiplyScalar(distance));obj.quaternion.copy(camera.quaternion);obj.rotateY(Math.PI);obj.scale.setScalar(.9);scene.add(obj);items.push(obj);selected=obj;toast('DUVAR ANKRAJI YERLEŞTİRİLDİ')}
function handleTap(e){if(e.target.closest('.toolbar,.panel,.topbar,.capture-stack,.center-card'))return;if(!started)return;const meta=catalog.find(x=>x[1]===current);if(!meta)return;meta[2]==='wall'?placeWall(e.clientX,e.clientY):placeFloor(e.clientX,e.clientY)}
function onMove(e){if(!xrScene||tracking!=='NORMAL')return;const meta=catalog.find(x=>x[1]===current);if(!meta||meta[2]!=='floor'){reticle.visible=false;return}const {camera}=xrScene;tap.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(tap,camera);const hit=raycaster.intersectObject(ground,false)[0];if(hit){reticle.visible=true;reticle.position.copy(hit.point);reticle.position.y=.008}else reticle.visible=false}
function save(){const data=items.map(x=>({type:x.userData.type,p:x.position.toArray(),q:x.quaternion.toArray(),s:x.scale.toArray()}));localStorage.setItem('mirrorrealm-home-v2',JSON.stringify(data));toast('ODA KAYDEDİLDİ')}
function loadSaved(){try{const data=JSON.parse(localStorage.getItem('mirrorrealm-home-v2')||'[]');for(const d of data){const o=make(d.type);o.position.fromArray(d.p);o.quaternion.fromArray(d.q);o.scale.fromArray(d.s);xrScene.scene.add(o);items.push(o)}}catch{}}
function clearAll(){if(!xrScene)return;items.splice(0).forEach(o=>xrScene.scene.remove(o));selected=null;localStorage.removeItem('mirrorrealm-home-v2');toast('ODA TEMİZLENDİ')}
function ui(){const grid=$('#elementGrid');catalog.forEach(([ico,name])=>{const b=document.createElement('button');b.innerHTML=`${ico}<span>${name.toUpperCase()}</span>`;b.onclick=()=>{current=name;[...grid.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#elementsPanel').classList.add('hidden');toast(name.toUpperCase()+' SEÇİLDİ')};grid.appendChild(b)});grid.firstChild?.classList.add('selected');$('#settingsBtn').onclick=()=>$('#settingsPanel').classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('[data-tool="catalog"]').onclick=()=>$('#elementsPanel').classList.remove('hidden');$('#rotateLeft').onclick=()=>{if(selected){selected.rotation.y+=Math.PI/8;toast('DÖNDÜRÜLDÜ')}};$('#scaleDown').onclick=()=>{if(selected)selected.scale.multiplyScalar(.88)};$('#scaleUp').onclick=()=>{if(selected)selected.scale.multiplyScalar(1.12)};$('#deleteBtn').onclick=()=>{if(selected&&xrScene){xrScene.scene.remove(selected);items.splice(items.indexOf(selected),1);selected=null;toast('SİLİNDİ')}};$('#clearBtn').onclick=clearAll;$('#saveBtn').onclick=save;const recenter=()=>{if(window.XR8){XR8.XrController.recenter();toast('WORLD RECENTERED')}};$('#recalibrateBtn').onclick=recenter;$('#recenterTop').onclick=recenter;canvas.addEventListener('pointerup',handleTap,true);canvas.addEventListener('pointermove',onMove,{passive:true})}
function startXR(){if(started)return;started=true;$('#permissionCard').classList.add('hidden');$('#scanHud').classList.remove('hidden');XR8.XrController.configure({disableWorldTracking:false,enableLighting:true,enableWorldPoints:true,scale:'responsive'});const statusModule={name:'mirrorrealm-status',onStart:()=>{initScene();$('#scanProgress').style.width='55%';$('#surfaceHud').classList.remove('hidden')},onUpdate:({processCpuResult})=>{const r=processCpuResult?.reality;if(!r)return;tracking=r.trackingStatus||'LIMITED';if(r.trackingReason==='INITIALIZING')tracking='INITIALIZING';updateStatus();if(tracking==='NORMAL'){ $('#scanProgress').style.width='100%';$('#scanHud').classList.add('hidden');$('#reticleHint').classList.remove('hidden');setTimeout(()=>$('#reticleHint').classList.add('hidden'),1800)}}};XR8.addCameraPipelineModules([XR8.GlTextureRenderer.pipelineModule(),XR8.Threejs.pipelineModule(),XR8.XrController.pipelineModule(),statusModule]);XR8.run({canvas,allowedDevices:XR8.XrConfig.device().MOBILE_AND_HEADSETS,cameraConfig:{direction:XR8.XrConfig.camera().BACK}})}
function boot(){ui();const go=()=>{$('#startBtn').onclick=startXR;$('#modeBadge').textContent='8TH WALL • READY'};window.XR8?go():window.addEventListener('xrloaded',go,{once:true})}boot();